version: "3.2"
services:
  api:
    build: .
    ports:
      - 8000:8000
    env_file: .env
    environment:
      - DB_HOST=postgres
    command: /venv/bin/python /venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app:ro
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastdb
    volumes:
      - fast-db:/var/lib/postgresql/data

volumes:
  fast-db:

