"""auto-votes

Revision ID: b7aef0176dd1
Revises: 2c56a2e3f335
Create Date: 2021-12-14 23:04:09.609411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b7aef0176dd1"
down_revision = "2c56a2e3f335"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "votes",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.pk"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.pk"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("post_id", "user_id"),
    )
    op.create_index(op.f("ix_posts_pk"), "posts", ["pk"], unique=False)
    op.create_index(op.f("ix_users_pk"), "users", ["pk"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_pk"), table_name="users")
    op.drop_index(op.f("ix_posts_pk"), table_name="posts")
    op.drop_table("votes")
    # ### end Alembic commands ###
