name: build fastapi

on: 
  push:
    branches: 
      - main
      - develop

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.11
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: install dependencies
        run: poetry install --no-interaction --no-root
      - name: run tests
        run: poetry run pytest -vv
